export interface Chapter {
  book: string;
  chapter: number;
  verseCount: number;
}

export const Chapters = [
    { book: "Genesis", chapter: 1, verseCount: 31 },
    { book: "Genesis", chapter: 2, verseCount: 25 },
    { book: "Genesis", chapter: 3, verseCount: 24 },
    { book: "Genesis", chapter: 4, verseCount: 26 },
    { book: "Genesis", chapter: 5, verseCount: 32 },
    { book: "Genesis", chapter: 6, verseCount: 22 },
    { book: "Genesis", chapter: 7, verseCount: 24 },
    { book: "Genesis", chapter: 8, verseCount: 22 },
    { book: "Genesis", chapter: 9, verseCount: 29 },
    { book: "Genesis", chapter: 10, verseCount: 32 },
    { book: "Genesis", chapter: 11, verseCount: 32 },
    { book: "Genesis", chapter: 12, verseCount: 20 },
    { book: "Genesis", chapter: 13, verseCount: 18 },
    { book: "Genesis", chapter: 14, verseCount: 24 },
    { book: "Genesis", chapter: 15, verseCount: 21 },
    { book: "Genesis", chapter: 16, verseCount: 16 },
    { book: "Genesis", chapter: 17, verseCount: 27 },
    { book: "Genesis", chapter: 18, verseCount: 33 },
    { book: "Genesis", chapter: 19, verseCount: 38 },
    { book: "Genesis", chapter: 20, verseCount: 18 },
    { book: "Genesis", chapter: 21, verseCount: 34 },
    { book: "Genesis", chapter: 22, verseCount: 24 },
    { book: "Genesis", chapter: 23, verseCount: 20 },
    { book: "Genesis", chapter: 24, verseCount: 67 },
    { book: "Genesis", chapter: 25, verseCount: 34 },
    { book: "Genesis", chapter: 26, verseCount: 35 },
    { book: "Genesis", chapter: 27, verseCount: 46 },
    { book: "Genesis", chapter: 28, verseCount: 22 },
    { book: "Genesis", chapter: 29, verseCount: 35 },
    { book: "Genesis", chapter: 30, verseCount: 43 },
    { book: "Genesis", chapter: 31, verseCount: 55 },
    { book: "Genesis", chapter: 32, verseCount: 32 },
    { book: "Genesis", chapter: 33, verseCount: 20 },
    { book: "Genesis", chapter: 34, verseCount: 31 },
    { book: "Genesis", chapter: 35, verseCount: 29 },
    { book: "Genesis", chapter: 36, verseCount: 43 },
    { book: "Genesis", chapter: 37, verseCount: 36 },
    { book: "Genesis", chapter: 38, verseCount: 30 },
    { book: "Genesis", chapter: 39, verseCount: 23 },
    { book: "Genesis", chapter: 40, verseCount: 23 },
    { book: "Genesis", chapter: 41, verseCount: 57 },
    { book: "Genesis", chapter: 42, verseCount: 38 },
    { book: "Genesis", chapter: 43, verseCount: 34 },
    { book: "Genesis", chapter: 44, verseCount: 34 },
    { book: "Genesis", chapter: 45, verseCount: 28 },
    { book: "Genesis", chapter: 46, verseCount: 34 },
    { book: "Genesis", chapter: 47, verseCount: 31 },
    { book: "Genesis", chapter: 48, verseCount: 22 },
    { book: "Genesis", chapter: 49, verseCount: 33 },
    { book: "Genesis", chapter: 50, verseCount: 26 },
    { book: "Exodus", chapter: 1, verseCount: 22 },
    { book: "Exodus", chapter: 2, verseCount: 25 },
    { book: "Exodus", chapter: 3, verseCount: 22 },
    { book: "Exodus", chapter: 4, verseCount: 31 },
    { book: "Exodus", chapter: 5, verseCount: 23 },
    { book: "Exodus", chapter: 6, verseCount: 30 },
    { book: "Exodus", chapter: 7, verseCount: 25 },
    { book: "Exodus", chapter: 8, verseCount: 32 },
    { book: "Exodus", chapter: 9, verseCount: 35 },
    { book: "Exodus", chapter: 10, verseCount: 29 },
    { book: "Exodus", chapter: 11, verseCount: 10 },
    { book: "Exodus", chapter: 12, verseCount: 51 },
    { book: "Exodus", chapter: 13, verseCount: 22 },
    { book: "Exodus", chapter: 14, verseCount: 31 },
    { book: "Exodus", chapter: 15, verseCount: 27 },
    { book: "Exodus", chapter: 16, verseCount: 36 },
    { book: "Exodus", chapter: 17, verseCount: 16 },
    { book: "Exodus", chapter: 18, verseCount: 27 },
    { book: "Exodus", chapter: 19, verseCount: 25 },
    { book: "Exodus", chapter: 20, verseCount: 26 },
    { book: "Exodus", chapter: 21, verseCount: 36 },
    { book: "Exodus", chapter: 22, verseCount: 31 },
    { book: "Exodus", chapter: 23, verseCount: 33 },
    { book: "Exodus", chapter: 24, verseCount: 18 },
    { book: "Exodus", chapter: 25, verseCount: 40 },
    { book: "Exodus", chapter: 26, verseCount: 37 },
    { book: "Exodus", chapter: 27, verseCount: 21 },
    { book: "Exodus", chapter: 28, verseCount: 43 },
    { book: "Exodus", chapter: 29, verseCount: 46 },
    { book: "Exodus", chapter: 30, verseCount: 38 },
    { book: "Exodus", chapter: 31, verseCount: 18 },
    { book: "Exodus", chapter: 32, verseCount: 35 },
    { book: "Exodus", chapter: 33, verseCount: 23 },
    { book: "Exodus", chapter: 34, verseCount: 35 },
    { book: "Exodus", chapter: 35, verseCount: 35 },
    { book: "Exodus", chapter: 36, verseCount: 38 },
    { book: "Exodus", chapter: 37, verseCount: 29 },
    { book: "Exodus", chapter: 38, verseCount: 31 },
    { book: "Exodus", chapter: 39, verseCount: 43 },
    { book: "Exodus", chapter: 40, verseCount: 38 },
    { book: "Leviticus", chapter: 1, verseCount: 17 },
    { book: "Leviticus", chapter: 2, verseCount: 16 },
    { book: "Leviticus", chapter: 3, verseCount: 17 },
    { book: "Leviticus", chapter: 4, verseCount: 35 },
    { book: "Leviticus", chapter: 5, verseCount: 19 },
    { book: "Leviticus", chapter: 6, verseCount: 30 },
    { book: "Leviticus", chapter: 7, verseCount: 38 },
    { book: "Leviticus", chapter: 8, verseCount: 36 },
    { book: "Leviticus", chapter: 9, verseCount: 24 },
    { book: "Leviticus", chapter: 10, verseCount: 20 },
    { book: "Leviticus", chapter: 11, verseCount: 47 },
    { book: "Leviticus", chapter: 12, verseCount: 8 },
    { book: "Leviticus", chapter: 13, verseCount: 59 },
    { book: "Leviticus", chapter: 14, verseCount: 57 },
    { book: "Leviticus", chapter: 15, verseCount: 33 },
    { book: "Leviticus", chapter: 16, verseCount: 34 },
    { book: "Leviticus", chapter: 17, verseCount: 16 },
    { book: "Leviticus", chapter: 18, verseCount: 30 },
    { book: "Leviticus", chapter: 19, verseCount: 37 },
    { book: "Leviticus", chapter: 20, verseCount: 27 },
    { book: "Leviticus", chapter: 21, verseCount: 24 },
    { book: "Leviticus", chapter: 22, verseCount: 33 },
    { book: "Leviticus", chapter: 23, verseCount: 44 },
    { book: "Leviticus", chapter: 24, verseCount: 23 },
    { book: "Leviticus", chapter: 25, verseCount: 55 },
    { book: "Leviticus", chapter: 26, verseCount: 46 },
    { book: "Leviticus", chapter: 27, verseCount: 34 },
    { book: "Numbers", chapter: 1, verseCount: 54 },
    { book: "Numbers", chapter: 2, verseCount: 34 },
    { book: "Numbers", chapter: 3, verseCount: 51 },
    { book: "Numbers", chapter: 4, verseCount: 49 },
    { book: "Numbers", chapter: 5, verseCount: 31 },
    { book: "Numbers", chapter: 6, verseCount: 27 },
    { book: "Numbers", chapter: 7, verseCount: 89 },
    { book: "Numbers", chapter: 8, verseCount: 26 },
    { book: "Numbers", chapter: 9, verseCount: 23 },
    { book: "Numbers", chapter: 10, verseCount: 36 },
    { book: "Numbers", chapter: 11, verseCount: 35 },
    { book: "Numbers", chapter: 12, verseCount: 16 },
    { book: "Numbers", chapter: 13, verseCount: 33 },
    { book: "Numbers", chapter: 14, verseCount: 45 },
    { book: "Numbers", chapter: 15, verseCount: 41 },
    { book: "Numbers", chapter: 16, verseCount: 50 },
    { book: "Numbers", chapter: 17, verseCount: 13 },
    { book: "Numbers", chapter: 18, verseCount: 32 },
    { book: "Numbers", chapter: 19, verseCount: 22 },
    { book: "Numbers", chapter: 20, verseCount: 29 },
    { book: "Numbers", chapter: 21, verseCount: 35 },
    { book: "Numbers", chapter: 22, verseCount: 41 },
    { book: "Numbers", chapter: 23, verseCount: 30 },
    { book: "Numbers", chapter: 24, verseCount: 25 },
    { book: "Numbers", chapter: 25, verseCount: 18 },
    { book: "Numbers", chapter: 26, verseCount: 65 },
    { book: "Numbers", chapter: 27, verseCount: 23 },
    { book: "Numbers", chapter: 28, verseCount: 31 },
    { book: "Numbers", chapter: 29, verseCount: 40 },
    { book: "Numbers", chapter: 30, verseCount: 16 },
    { book: "Numbers", chapter: 31, verseCount: 54 },
    { book: "Numbers", chapter: 32, verseCount: 42 },
    { book: "Numbers", chapter: 33, verseCount: 56 },
    { book: "Numbers", chapter: 34, verseCount: 29 },
    { book: "Numbers", chapter: 35, verseCount: 34 },
    { book: "Numbers", chapter: 36, verseCount: 13 },
    { book: "Deuteronomy", chapter: 1, verseCount: 46 },
    { book: "Deuteronomy", chapter: 2, verseCount: 37 },
    { book: "Deuteronomy", chapter: 3, verseCount: 29 },
    { book: "Deuteronomy", chapter: 4, verseCount: 49 },
    { book: "Deuteronomy", chapter: 5, verseCount: 33 },
    { book: "Deuteronomy", chapter: 6, verseCount: 25 },
    { book: "Deuteronomy", chapter: 7, verseCount: 26 },
    { book: "Deuteronomy", chapter: 8, verseCount: 20 },
    { book: "Deuteronomy", chapter: 9, verseCount: 29 },
    { book: "Deuteronomy", chapter: 10, verseCount: 22 },
    { book: "Deuteronomy", chapter: 11, verseCount: 32 },
    { book: "Deuteronomy", chapter: 12, verseCount: 32 },
    { book: "Deuteronomy", chapter: 13, verseCount: 18 },
    { book: "Deuteronomy", chapter: 14, verseCount: 29 },
    { book: "Deuteronomy", chapter: 15, verseCount: 23 },
    { book: "Deuteronomy", chapter: 16, verseCount: 22 },
    { book: "Deuteronomy", chapter: 17, verseCount: 20 },
    { book: "Deuteronomy", chapter: 18, verseCount: 22 },
    { book: "Deuteronomy", chapter: 19, verseCount: 21 },
    { book: "Deuteronomy", chapter: 20, verseCount: 20 },
    { book: "Deuteronomy", chapter: 21, verseCount: 23 },
    { book: "Deuteronomy", chapter: 22, verseCount: 30 },
    { book: "Deuteronomy", chapter: 23, verseCount: 25 },
    { book: "Deuteronomy", chapter: 24, verseCount: 22 },
    { book: "Deuteronomy", chapter: 25, verseCount: 19 },
    { book: "Deuteronomy", chapter: 26, verseCount: 19 },
    { book: "Deuteronomy", chapter: 27, verseCount: 26 },
    { book: "Deuteronomy", chapter: 28, verseCount: 68 },
    { book: "Deuteronomy", chapter: 29, verseCount: 29 },
    { book: "Deuteronomy", chapter: 30, verseCount: 20 },
    { book: "Deuteronomy", chapter: 31, verseCount: 30 },
    { book: "Deuteronomy", chapter: 32, verseCount: 52 },
    { book: "Deuteronomy", chapter: 33, verseCount: 29 },
    { book: "Deuteronomy", chapter: 34, verseCount: 12 },
    { book: "Joshua", chapter: 1, verseCount: 18 },
    { book: "Joshua", chapter: 2, verseCount: 24 },
    { book: "Joshua", chapter: 3, verseCount: 17 },
    { book: "Joshua", chapter: 4, verseCount: 24 },
    { book: "Joshua", chapter: 5, verseCount: 15 },
    { book: "Joshua", chapter: 6, verseCount: 27 },
    { book: "Joshua", chapter: 7, verseCount: 26 },
    { book: "Joshua", chapter: 8, verseCount: 35 },
    { book: "Joshua", chapter: 9, verseCount: 27 },
    { book: "Joshua", chapter: 10, verseCount: 43 },
    { book: "Joshua", chapter: 11, verseCount: 23 },
    { book: "Joshua", chapter: 12, verseCount: 24 },
    { book: "Joshua", chapter: 13, verseCount: 33 },
    { book: "Joshua", chapter: 14, verseCount: 15 },
    { book: "Joshua", chapter: 15, verseCount: 63 },
    { book: "Joshua", chapter: 16, verseCount: 10 },
    { book: "Joshua", chapter: 17, verseCount: 18 },
    { book: "Joshua", chapter: 18, verseCount: 28 },
    { book: "Joshua", chapter: 19, verseCount: 51 },
    { book: "Joshua", chapter: 20, verseCount: 9 },
    { book: "Joshua", chapter: 21, verseCount: 45 },
    { book: "Joshua", chapter: 22, verseCount: 34 },
    { book: "Joshua", chapter: 23, verseCount: 16 },
    { book: "Joshua", chapter: 24, verseCount: 33 },
    { book: "Judges", chapter: 1, verseCount: 36 },
    { book: "Judges", chapter: 2, verseCount: 23 },
    { book: "Judges", chapter: 3, verseCount: 31 },
    { book: "Judges", chapter: 4, verseCount: 24 },
    { book: "Judges", chapter: 5, verseCount: 31 },
    { book: "Judges", chapter: 6, verseCount: 40 },
    { book: "Judges", chapter: 7, verseCount: 25 },
    { book: "Judges", chapter: 8, verseCount: 35 },
    { book: "Judges", chapter: 9, verseCount: 57 },
    { book: "Judges", chapter: 10, verseCount: 18 },
    { book: "Judges", chapter: 11, verseCount: 40 },
    { book: "Judges", chapter: 12, verseCount: 15 },
    { book: "Judges", chapter: 13, verseCount: 25 },
    { book: "Judges", chapter: 14, verseCount: 20 },
    { book: "Judges", chapter: 15, verseCount: 20 },
    { book: "Judges", chapter: 16, verseCount: 31 },
    { book: "Judges", chapter: 17, verseCount: 13 },
    { book: "Judges", chapter: 18, verseCount: 31 },
    { book: "Judges", chapter: 19, verseCount: 30 },
    { book: "Judges", chapter: 20, verseCount: 48 },
    { book: "Judges", chapter: 21, verseCount: 25 },
    { book: "Ruth", chapter: 1, verseCount: 22 },
    { book: "Ruth", chapter: 2, verseCount: 23 },
    { book: "Ruth", chapter: 3, verseCount: 18 },
    { book: "Ruth", chapter: 4, verseCount: 22 },
    { book: "1 Samuel", chapter: 1, verseCount: 28 },
    { book: "1 Samuel", chapter: 2, verseCount: 36 },
    { book: "1 Samuel", chapter: 3, verseCount: 21 },
    { book: "1 Samuel", chapter: 4, verseCount: 22 },
    { book: "1 Samuel", chapter: 5, verseCount: 12 },
    { book: "1 Samuel", chapter: 6, verseCount: 21 },
    { book: "1 Samuel", chapter: 7, verseCount: 17 },
    { book: "1 Samuel", chapter: 8, verseCount: 22 },
    { book: "1 Samuel", chapter: 9, verseCount: 27 },
    { book: "1 Samuel", chapter: 10, verseCount: 27 },
    { book: "1 Samuel", chapter: 11, verseCount: 15 },
    { book: "1 Samuel", chapter: 12, verseCount: 25 },
    { book: "1 Samuel", chapter: 13, verseCount: 23 },
    { book: "1 Samuel", chapter: 14, verseCount: 52 },
    { book: "1 Samuel", chapter: 15, verseCount: 35 },
    { book: "1 Samuel", chapter: 16, verseCount: 23 },
    { book: "1 Samuel", chapter: 17, verseCount: 58 },
    { book: "1 Samuel", chapter: 18, verseCount: 30 },
    { book: "1 Samuel", chapter: 19, verseCount: 24 },
    { book: "1 Samuel", chapter: 20, verseCount: 42 },
    { book: "1 Samuel", chapter: 21, verseCount: 15 },
    { book: "1 Samuel", chapter: 22, verseCount: 23 },
    { book: "1 Samuel", chapter: 23, verseCount: 29 },
    { book: "1 Samuel", chapter: 24, verseCount: 22 },
    { book: "1 Samuel", chapter: 25, verseCount: 44 },
    { book: "1 Samuel", chapter: 26, verseCount: 25 },
    { book: "1 Samuel", chapter: 27, verseCount: 12 },
    { book: "1 Samuel", chapter: 28, verseCount: 25 },
    { book: "1 Samuel", chapter: 29, verseCount: 11 },
    { book: "1 Samuel", chapter: 30, verseCount: 31 },
    { book: "1 Samuel", chapter: 31, verseCount: 13 },
    { book: "2 Samuel", chapter: 1, verseCount: 27 },
    { book: "2 Samuel", chapter: 2, verseCount: 32 },
    { book: "2 Samuel", chapter: 3, verseCount: 39 },
    { book: "2 Samuel", chapter: 4, verseCount: 12 },
    { book: "2 Samuel", chapter: 5, verseCount: 25 },
    { book: "2 Samuel", chapter: 6, verseCount: 23 },
    { book: "2 Samuel", chapter: 7, verseCount: 29 },
    { book: "2 Samuel", chapter: 8, verseCount: 18 },
    { book: "2 Samuel", chapter: 9, verseCount: 13 },
    { book: "2 Samuel", chapter: 10, verseCount: 19 },
    { book: "2 Samuel", chapter: 11, verseCount: 27 },
    { book: "2 Samuel", chapter: 12, verseCount: 31 },
    { book: "2 Samuel", chapter: 13, verseCount: 39 },
    { book: "2 Samuel", chapter: 14, verseCount: 33 },
    { book: "2 Samuel", chapter: 15, verseCount: 37 },
    { book: "2 Samuel", chapter: 16, verseCount: 23 },
    { book: "2 Samuel", chapter: 17, verseCount: 29 },
    { book: "2 Samuel", chapter: 18, verseCount: 33 },
    { book: "2 Samuel", chapter: 19, verseCount: 43 },
    { book: "2 Samuel", chapter: 20, verseCount: 26 },
    { book: "2 Samuel", chapter: 21, verseCount: 22 },
    { book: "2 Samuel", chapter: 22, verseCount: 51 },
    { book: "2 Samuel", chapter: 23, verseCount: 39 },
    { book: "2 Samuel", chapter: 24, verseCount: 25 },
    { book: "1 Kings", chapter: 1, verseCount: 53 },
    { book: "1 Kings", chapter: 2, verseCount: 46 },
    { book: "1 Kings", chapter: 3, verseCount: 28 },
    { book: "1 Kings", chapter: 4, verseCount: 34 },
    { book: "1 Kings", chapter: 5, verseCount: 18 },
    { book: "1 Kings", chapter: 6, verseCount: 38 },
    { book: "1 Kings", chapter: 7, verseCount: 51 },
    { book: "1 Kings", chapter: 8, verseCount: 66 },
    { book: "1 Kings", chapter: 9, verseCount: 28 },
    { book: "1 Kings", chapter: 10, verseCount: 29 },
    { book: "1 Kings", chapter: 11, verseCount: 43 },
    { book: "1 Kings", chapter: 12, verseCount: 33 },
    { book: "1 Kings", chapter: 13, verseCount: 34 },
    { book: "1 Kings", chapter: 14, verseCount: 31 },
    { book: "1 Kings", chapter: 15, verseCount: 34 },
    { book: "1 Kings", chapter: 16, verseCount: 34 },
    { book: "1 Kings", chapter: 17, verseCount: 24 },
    { book: "1 Kings", chapter: 18, verseCount: 46 },
    { book: "1 Kings", chapter: 19, verseCount: 21 },
    { book: "1 Kings", chapter: 20, verseCount: 43 },
    { book: "1 Kings", chapter: 21, verseCount: 29 },
    { book: "1 Kings", chapter: 22, verseCount: 53 },
    { book: "2 Kings", chapter: 1, verseCount: 18 },
    { book: "2 Kings", chapter: 2, verseCount: 25 },
    { book: "2 Kings", chapter: 3, verseCount: 27 },
    { book: "2 Kings", chapter: 4, verseCount: 44 },
    { book: "2 Kings", chapter: 5, verseCount: 27 },
    { book: "2 Kings", chapter: 6, verseCount: 33 },
    { book: "2 Kings", chapter: 7, verseCount: 20 },
    { book: "2 Kings", chapter: 8, verseCount: 29 },
    { book: "2 Kings", chapter: 9, verseCount: 37 },
    { book: "2 Kings", chapter: 10, verseCount: 36 },
    { book: "2 Kings", chapter: 11, verseCount: 21 },
    { book: "2 Kings", chapter: 12, verseCount: 21 },
    { book: "2 Kings", chapter: 13, verseCount: 25 },
    { book: "2 Kings", chapter: 14, verseCount: 29 },
    { book: "2 Kings", chapter: 15, verseCount: 38 },
    { book: "2 Kings", chapter: 16, verseCount: 20 },
    { book: "2 Kings", chapter: 17, verseCount: 41 },
    { book: "2 Kings", chapter: 18, verseCount: 37 },
    { book: "2 Kings", chapter: 19, verseCount: 37 },
    { book: "2 Kings", chapter: 20, verseCount: 21 },
    { book: "2 Kings", chapter: 21, verseCount: 26 },
    { book: "2 Kings", chapter: 22, verseCount: 20 },
    { book: "2 Kings", chapter: 23, verseCount: 37 },
    { book: "2 Kings", chapter: 24, verseCount: 20 },
    { book: "2 Kings", chapter: 25, verseCount: 30 },
    { book: "1 Chronicles", chapter: 1, verseCount: 54 },
    { book: "1 Chronicles", chapter: 2, verseCount: 55 },
    { book: "1 Chronicles", chapter: 3, verseCount: 24 },
    { book: "1 Chronicles", chapter: 4, verseCount: 43 },
    { book: "1 Chronicles", chapter: 5, verseCount: 26 },
    { book: "1 Chronicles", chapter: 6, verseCount: 81 },
    { book: "1 Chronicles", chapter: 7, verseCount: 40 },
    { book: "1 Chronicles", chapter: 8, verseCount: 40 },
    { book: "1 Chronicles", chapter: 9, verseCount: 44 },
    { book: "1 Chronicles", chapter: 10, verseCount: 14 },
    { book: "1 Chronicles", chapter: 11, verseCount: 47 },
    { book: "1 Chronicles", chapter: 12, verseCount: 40 },
    { book: "1 Chronicles", chapter: 13, verseCount: 14 },
    { book: "1 Chronicles", chapter: 14, verseCount: 17 },
    { book: "1 Chronicles", chapter: 15, verseCount: 29 },
    { book: "1 Chronicles", chapter: 16, verseCount: 43 },
    { book: "1 Chronicles", chapter: 17, verseCount: 27 },
    { book: "1 Chronicles", chapter: 18, verseCount: 17 },
    { book: "1 Chronicles", chapter: 19, verseCount: 19 },
    { book: "1 Chronicles", chapter: 20, verseCount: 8 },
    { book: "1 Chronicles", chapter: 21, verseCount: 30 },
    { book: "1 Chronicles", chapter: 22, verseCount: 19 },
    { book: "1 Chronicles", chapter: 23, verseCount: 32 },
    { book: "1 Chronicles", chapter: 24, verseCount: 31 },
    { book: "1 Chronicles", chapter: 25, verseCount: 31 },
    { book: "1 Chronicles", chapter: 26, verseCount: 32 },
    { book: "1 Chronicles", chapter: 27, verseCount: 34 },
    { book: "1 Chronicles", chapter: 28, verseCount: 21 },
    { book: "1 Chronicles", chapter: 29, verseCount: 30 },
    { book: "2 Chronicles", chapter: 1, verseCount: 17 },
    { book: "2 Chronicles", chapter: 2, verseCount: 18 },
    { book: "2 Chronicles", chapter: 3, verseCount: 17 },
    { book: "2 Chronicles", chapter: 4, verseCount: 22 },
    { book: "2 Chronicles", chapter: 5, verseCount: 14 },
    { book: "2 Chronicles", chapter: 6, verseCount: 42 },
    { book: "2 Chronicles", chapter: 7, verseCount: 22 },
    { book: "2 Chronicles", chapter: 8, verseCount: 18 },
    { book: "2 Chronicles", chapter: 9, verseCount: 31 },
    { book: "2 Chronicles", chapter: 10, verseCount: 19 },
    { book: "2 Chronicles", chapter: 11, verseCount: 23 },
    { book: "2 Chronicles", chapter: 12, verseCount: 16 },
    { book: "2 Chronicles", chapter: 13, verseCount: 22 },
    { book: "2 Chronicles", chapter: 14, verseCount: 15 },
    { book: "2 Chronicles", chapter: 15, verseCount: 19 },
    { book: "2 Chronicles", chapter: 16, verseCount: 14 },
    { book: "2 Chronicles", chapter: 17, verseCount: 19 },
    { book: "2 Chronicles", chapter: 18, verseCount: 34 },
    { book: "2 Chronicles", chapter: 19, verseCount: 11 },
    { book: "2 Chronicles", chapter: 20, verseCount: 37 },
    { book: "2 Chronicles", chapter: 21, verseCount: 20 },
    { book: "2 Chronicles", chapter: 22, verseCount: 12 },
    { book: "2 Chronicles", chapter: 23, verseCount: 21 },
    { book: "2 Chronicles", chapter: 24, verseCount: 27 },
    { book: "2 Chronicles", chapter: 25, verseCount: 28 },
    { book: "2 Chronicles", chapter: 26, verseCount: 23 },
    { book: "2 Chronicles", chapter: 27, verseCount: 9 },
    { book: "2 Chronicles", chapter: 28, verseCount: 27 },
    { book: "2 Chronicles", chapter: 29, verseCount: 36 },
    { book: "2 Chronicles", chapter: 30, verseCount: 27 },
    { book: "2 Chronicles", chapter: 31, verseCount: 21 },
    { book: "2 Chronicles", chapter: 32, verseCount: 33 },
    { book: "2 Chronicles", chapter: 33, verseCount: 25 },
    { book: "2 Chronicles", chapter: 34, verseCount: 33 },
    { book: "2 Chronicles", chapter: 35, verseCount: 27 },
    { book: "2 Chronicles", chapter: 36, verseCount: 23 },
    { book: "Ezra", chapter: 1, verseCount: 11 },
    { book: "Ezra", chapter: 2, verseCount: 70 },
    { book: "Ezra", chapter: 3, verseCount: 13 },
    { book: "Ezra", chapter: 4, verseCount: 24 },
    { book: "Ezra", chapter: 5, verseCount: 17 },
    { book: "Ezra", chapter: 6, verseCount: 22 },
    { book: "Ezra", chapter: 7, verseCount: 28 },
    { book: "Ezra", chapter: 8, verseCount: 36 },
    { book: "Ezra", chapter: 9, verseCount: 15 },
    { book: "Ezra", chapter: 10, verseCount: 44 },
    { book: "Nehemiah", chapter: 1, verseCount: 11 },
    { book: "Nehemiah", chapter: 2, verseCount: 20 },
    { book: "Nehemiah", chapter: 3, verseCount: 32 },
    { book: "Nehemiah", chapter: 4, verseCount: 23 },
    { book: "Nehemiah", chapter: 5, verseCount: 19 },
    { book: "Nehemiah", chapter: 6, verseCount: 19 },
    { book: "Nehemiah", chapter: 7, verseCount: 73 },
    { book: "Nehemiah", chapter: 8, verseCount: 18 },
    { book: "Nehemiah", chapter: 9, verseCount: 38 },
    { book: "Nehemiah", chapter: 10, verseCount: 39 },
    { book: "Nehemiah", chapter: 11, verseCount: 36 },
    { book: "Nehemiah", chapter: 12, verseCount: 47 },
    { book: "Nehemiah", chapter: 13, verseCount: 31 },
    { book: "Esther", chapter: 1, verseCount: 22 },
    { book: "Esther", chapter: 2, verseCount: 23 },
    { book: "Esther", chapter: 3, verseCount: 15 },
    { book: "Esther", chapter: 4, verseCount: 17 },
    { book: "Esther", chapter: 5, verseCount: 14 },
    { book: "Esther", chapter: 6, verseCount: 14 },
    { book: "Esther", chapter: 7, verseCount: 10 },
    { book: "Esther", chapter: 8, verseCount: 17 },
    { book: "Esther", chapter: 9, verseCount: 32 },
    { book: "Esther", chapter: 10, verseCount: 3 },
    { book: "Job", chapter: 1, verseCount: 22 },
    { book: "Job", chapter: 2, verseCount: 13 },
    { book: "Job", chapter: 3, verseCount: 26 },
    { book: "Job", chapter: 4, verseCount: 21 },
    { book: "Job", chapter: 5, verseCount: 27 },
    { book: "Job", chapter: 6, verseCount: 30 },
    { book: "Job", chapter: 7, verseCount: 21 },
    { book: "Job", chapter: 8, verseCount: 22 },
    { book: "Job", chapter: 9, verseCount: 35 },
    { book: "Job", chapter: 10, verseCount: 22 },
    { book: "Job", chapter: 11, verseCount: 20 },
    { book: "Job", chapter: 12, verseCount: 25 },
    { book: "Job", chapter: 13, verseCount: 28 },
    { book: "Job", chapter: 14, verseCount: 22 },
    { book: "Job", chapter: 15, verseCount: 35 },
    { book: "Job", chapter: 16, verseCount: 22 },
    { book: "Job", chapter: 17, verseCount: 16 },
    { book: "Job", chapter: 18, verseCount: 21 },
    { book: "Job", chapter: 19, verseCount: 29 },
    { book: "Job", chapter: 20, verseCount: 29 },
    { book: "Job", chapter: 21, verseCount: 34 },
    { book: "Job", chapter: 22, verseCount: 30 },
    { book: "Job", chapter: 23, verseCount: 17 },
    { book: "Job", chapter: 24, verseCount: 25 },
    { book: "Job", chapter: 25, verseCount: 6 },
    { book: "Job", chapter: 26, verseCount: 14 },
    { book: "Job", chapter: 27, verseCount: 23 },
    { book: "Job", chapter: 28, verseCount: 28 },
    { book: "Job", chapter: 29, verseCount: 25 },
    { book: "Job", chapter: 30, verseCount: 31 },
    { book: "Job", chapter: 31, verseCount: 40 },
    { book: "Job", chapter: 32, verseCount: 22 },
    { book: "Job", chapter: 33, verseCount: 33 },
    { book: "Job", chapter: 34, verseCount: 37 },
    { book: "Job", chapter: 35, verseCount: 16 },
    { book: "Job", chapter: 36, verseCount: 33 },
    { book: "Job", chapter: 37, verseCount: 24 },
    { book: "Job", chapter: 38, verseCount: 41 },
    { book: "Job", chapter: 39, verseCount: 30 },
    { book: "Job", chapter: 40, verseCount: 24 },
    { book: "Job", chapter: 41, verseCount: 34 },
    { book: "Job", chapter: 42, verseCount: 17 },
    { book: "Psalms", chapter: 1, verseCount: 6 },
    { book: "Psalms", chapter: 2, verseCount: 12 },
    { book: "Psalms", chapter: 3, verseCount: 8 },
    { book: "Psalms", chapter: 4, verseCount: 8 },
    { book: "Psalms", chapter: 5, verseCount: 12 },
    { book: "Psalms", chapter: 6, verseCount: 10 },
    { book: "Psalms", chapter: 7, verseCount: 17 },
    { book: "Psalms", chapter: 8, verseCount: 9 },
    { book: "Psalms", chapter: 9, verseCount: 20 },
    { book: "Psalms", chapter: 10, verseCount: 18 },
    { book: "Psalms", chapter: 11, verseCount: 7 },
    { book: "Psalms", chapter: 12, verseCount: 8 },
    { book: "Psalms", chapter: 13, verseCount: 6 },
    { book: "Psalms", chapter: 14, verseCount: 7 },
    { book: "Psalms", chapter: 15, verseCount: 5 },
    { book: "Psalms", chapter: 16, verseCount: 11 },
    { book: "Psalms", chapter: 17, verseCount: 15 },
    { book: "Psalms", chapter: 18, verseCount: 50 },
    { book: "Psalms", chapter: 19, verseCount: 14 },
    { book: "Psalms", chapter: 20, verseCount: 9 },
    { book: "Psalms", chapter: 21, verseCount: 13 },
    { book: "Psalms", chapter: 22, verseCount: 31 },
    { book: "Psalms", chapter: 23, verseCount: 6 },
    { book: "Psalms", chapter: 24, verseCount: 10 },
    { book: "Psalms", chapter: 25, verseCount: 22 },
    { book: "Psalms", chapter: 26, verseCount: 12 },
    { book: "Psalms", chapter: 27, verseCount: 14 },
    { book: "Psalms", chapter: 28, verseCount: 9 },
    { book: "Psalms", chapter: 29, verseCount: 11 },
    { book: "Psalms", chapter: 30, verseCount: 12 },
    { book: "Psalms", chapter: 31, verseCount: 24 },
    { book: "Psalms", chapter: 32, verseCount: 11 },
    { book: "Psalms", chapter: 33, verseCount: 22 },
    { book: "Psalms", chapter: 34, verseCount: 22 },
    { book: "Psalms", chapter: 35, verseCount: 28 },
    { book: "Psalms", chapter: 36, verseCount: 12 },
    { book: "Psalms", chapter: 37, verseCount: 40 },
    { book: "Psalms", chapter: 38, verseCount: 22 },
    { book: "Psalms", chapter: 39, verseCount: 13 },
    { book: "Psalms", chapter: 40, verseCount: 17 },
    { book: "Psalms", chapter: 41, verseCount: 13 },
    { book: "Psalms", chapter: 42, verseCount: 11 },
    { book: "Psalms", chapter: 43, verseCount: 5 },
    { book: "Psalms", chapter: 44, verseCount: 26 },
    { book: "Psalms", chapter: 45, verseCount: 17 },
    { book: "Psalms", chapter: 46, verseCount: 11 },
    { book: "Psalms", chapter: 47, verseCount: 9 },
    { book: "Psalms", chapter: 48, verseCount: 14 },
    { book: "Psalms", chapter: 49, verseCount: 20 },
    { book: "Psalms", chapter: 50, verseCount: 23 },
    { book: "Psalms", chapter: 51, verseCount: 19 },
    { book: "Psalms", chapter: 52, verseCount: 9 },
    { book: "Psalms", chapter: 53, verseCount: 6 },
    { book: "Psalms", chapter: 54, verseCount: 7 },
    { book: "Psalms", chapter: 55, verseCount: 23 },
    { book: "Psalms", chapter: 56, verseCount: 13 },
    { book: "Psalms", chapter: 57, verseCount: 11 },
    { book: "Psalms", chapter: 58, verseCount: 11 },
    { book: "Psalms", chapter: 59, verseCount: 17 },
    { book: "Psalms", chapter: 60, verseCount: 12 },
    { book: "Psalms", chapter: 61, verseCount: 8 },
    { book: "Psalms", chapter: 62, verseCount: 12 },
    { book: "Psalms", chapter: 63, verseCount: 11 },
    { book: "Psalms", chapter: 64, verseCount: 10 },
    { book: "Psalms", chapter: 65, verseCount: 13 },
    { book: "Psalms", chapter: 66, verseCount: 20 },
    { book: "Psalms", chapter: 67, verseCount: 7 },
    { book: "Psalms", chapter: 68, verseCount: 35 },
    { book: "Psalms", chapter: 69, verseCount: 36 },
    { book: "Psalms", chapter: 70, verseCount: 5 },
    { book: "Psalms", chapter: 71, verseCount: 24 },
    { book: "Psalms", chapter: 72, verseCount: 20 },
    { book: "Psalms", chapter: 73, verseCount: 28 },
    { book: "Psalms", chapter: 74, verseCount: 23 },
    { book: "Psalms", chapter: 75, verseCount: 10 },
    { book: "Psalms", chapter: 76, verseCount: 12 },
    { book: "Psalms", chapter: 77, verseCount: 20 },
    { book: "Psalms", chapter: 78, verseCount: 72 },
    { book: "Psalms", chapter: 79, verseCount: 13 },
    { book: "Psalms", chapter: 80, verseCount: 19 },
    { book: "Psalms", chapter: 81, verseCount: 16 },
    { book: "Psalms", chapter: 82, verseCount: 8 },
    { book: "Psalms", chapter: 83, verseCount: 18 },
    { book: "Psalms", chapter: 84, verseCount: 12 },
    { book: "Psalms", chapter: 85, verseCount: 13 },
    { book: "Psalms", chapter: 86, verseCount: 17 },
    { book: "Psalms", chapter: 87, verseCount: 7 },
    { book: "Psalms", chapter: 88, verseCount: 18 },
    { book: "Psalms", chapter: 89, verseCount: 52 },
    { book: "Psalms", chapter: 90, verseCount: 17 },
    { book: "Psalms", chapter: 91, verseCount: 16 },
    { book: "Psalms", chapter: 92, verseCount: 15 },
    { book: "Psalms", chapter: 93, verseCount: 5 },
    { book: "Psalms", chapter: 94, verseCount: 23 },
    { book: "Psalms", chapter: 95, verseCount: 11 },
    { book: "Psalms", chapter: 96, verseCount: 13 },
    { book: "Psalms", chapter: 97, verseCount: 12 },
    { book: "Psalms", chapter: 98, verseCount: 9 },
    { book: "Psalms", chapter: 99, verseCount: 9 },
    { book: "Psalms", chapter: 100, verseCount: 5 },
    { book: "Psalms", chapter: 101, verseCount: 8 },
    { book: "Psalms", chapter: 102, verseCount: 28 },
    { book: "Psalms", chapter: 103, verseCount: 22 },
    { book: "Psalms", chapter: 104, verseCount: 35 },
    { book: "Psalms", chapter: 105, verseCount: 45 },
    { book: "Psalms", chapter: 106, verseCount: 48 },
    { book: "Psalms", chapter: 107, verseCount: 43 },
    { book: "Psalms", chapter: 108, verseCount: 13 },
    { book: "Psalms", chapter: 109, verseCount: 31 },
    { book: "Psalms", chapter: 110, verseCount: 7 },
    { book: "Psalms", chapter: 111, verseCount: 10 },
    { book: "Psalms", chapter: 112, verseCount: 10 },
    { book: "Psalms", chapter: 113, verseCount: 9 },
    { book: "Psalms", chapter: 114, verseCount: 8 },
    { book: "Psalms", chapter: 115, verseCount: 18 },
    { book: "Psalms", chapter: 116, verseCount: 19 },
    { book: "Psalms", chapter: 117, verseCount: 2 },
    { book: "Psalms", chapter: 118, verseCount: 29 },
    { book: "Psalms", chapter: 119, verseCount: 176 },
    { book: "Psalms", chapter: 120, verseCount: 7 },
    { book: "Psalms", chapter: 121, verseCount: 8 },
    { book: "Psalms", chapter: 122, verseCount: 9 },
    { book: "Psalms", chapter: 123, verseCount: 4 },
    { book: "Psalms", chapter: 124, verseCount: 8 },
    { book: "Psalms", chapter: 125, verseCount: 5 },
    { book: "Psalms", chapter: 126, verseCount: 6 },
    { book: "Psalms", chapter: 127, verseCount: 5 },
    { book: "Psalms", chapter: 128, verseCount: 6 },
    { book: "Psalms", chapter: 129, verseCount: 8 },
    { book: "Psalms", chapter: 130, verseCount: 8 },
    { book: "Psalms", chapter: 131, verseCount: 3 },
    { book: "Psalms", chapter: 132, verseCount: 18 },
    { book: "Psalms", chapter: 133, verseCount: 3 },
    { book: "Psalms", chapter: 134, verseCount: 3 },
    { book: "Psalms", chapter: 135, verseCount: 21 },
    { book: "Psalms", chapter: 136, verseCount: 26 },
    { book: "Psalms", chapter: 137, verseCount: 9 },
    { book: "Psalms", chapter: 138, verseCount: 8 },
    { book: "Psalms", chapter: 139, verseCount: 24 },
    { book: "Psalms", chapter: 140, verseCount: 13 },
    { book: "Psalms", chapter: 141, verseCount: 10 },
    { book: "Psalms", chapter: 142, verseCount: 7 },
    { book: "Psalms", chapter: 143, verseCount: 12 },
    { book: "Psalms", chapter: 144, verseCount: 15 },
    { book: "Psalms", chapter: 145, verseCount: 21 },
    { book: "Psalms", chapter: 146, verseCount: 10 },
    { book: "Psalms", chapter: 147, verseCount: 20 },
    { book: "Psalms", chapter: 148, verseCount: 14 },
    { book: "Psalms", chapter: 149, verseCount: 9 },
    { book: "Psalms", chapter: 150, verseCount: 6 },
    { book: "Proverbs", chapter: 1, verseCount: 33 },
    { book: "Proverbs", chapter: 2, verseCount: 22 },
    { book: "Proverbs", chapter: 3, verseCount: 35 },
    { book: "Proverbs", chapter: 4, verseCount: 27 },
    { book: "Proverbs", chapter: 5, verseCount: 23 },
    { book: "Proverbs", chapter: 6, verseCount: 35 },
    { book: "Proverbs", chapter: 7, verseCount: 27 },
    { book: "Proverbs", chapter: 8, verseCount: 36 },
    { book: "Proverbs", chapter: 9, verseCount: 18 },
    { book: "Proverbs", chapter: 10, verseCount: 32 },
    { book: "Proverbs", chapter: 11, verseCount: 31 },
    { book: "Proverbs", chapter: 12, verseCount: 28 },
    { book: "Proverbs", chapter: 13, verseCount: 25 },
    { book: "Proverbs", chapter: 14, verseCount: 35 },
    { book: "Proverbs", chapter: 15, verseCount: 33 },
    { book: "Proverbs", chapter: 16, verseCount: 33 },
    { book: "Proverbs", chapter: 17, verseCount: 28 },
    { book: "Proverbs", chapter: 18, verseCount: 24 },
    { book: "Proverbs", chapter: 19, verseCount: 29 },
    { book: "Proverbs", chapter: 20, verseCount: 30 },
    { book: "Proverbs", chapter: 21, verseCount: 31 },
    { book: "Proverbs", chapter: 22, verseCount: 29 },
    { book: "Proverbs", chapter: 23, verseCount: 35 },
    { book: "Proverbs", chapter: 24, verseCount: 34 },
    { book: "Proverbs", chapter: 25, verseCount: 28 },
    { book: "Proverbs", chapter: 26, verseCount: 28 },
    { book: "Proverbs", chapter: 27, verseCount: 27 },
    { book: "Proverbs", chapter: 28, verseCount: 28 },
    { book: "Proverbs", chapter: 29, verseCount: 27 },
    { book: "Proverbs", chapter: 30, verseCount: 33 },
    { book: "Proverbs", chapter: 31, verseCount: 31 },
    { book: "Ecclesiastes", chapter: 1, verseCount: 18 },
    { book: "Ecclesiastes", chapter: 2, verseCount: 26 },
    { book: "Ecclesiastes", chapter: 3, verseCount: 22 },
    { book: "Ecclesiastes", chapter: 4, verseCount: 16 },
    { book: "Ecclesiastes", chapter: 5, verseCount: 20 },
    { book: "Ecclesiastes", chapter: 6, verseCount: 12 },
    { book: "Ecclesiastes", chapter: 7, verseCount: 29 },
    { book: "Ecclesiastes", chapter: 8, verseCount: 17 },
    { book: "Ecclesiastes", chapter: 9, verseCount: 18 },
    { book: "Ecclesiastes", chapter: 10, verseCount: 20 },
    { book: "Ecclesiastes", chapter: 11, verseCount: 10 },
    { book: "Ecclesiastes", chapter: 12, verseCount: 14 },
    { book: "Song of Solomon", chapter: 1, verseCount: 17 },
    { book: "Song of Solomon", chapter: 2, verseCount: 17 },
    { book: "Song of Solomon", chapter: 3, verseCount: 11 },
    { book: "Song of Solomon", chapter: 4, verseCount: 16 },
    { book: "Song of Solomon", chapter: 5, verseCount: 16 },
    { book: "Song of Solomon", chapter: 6, verseCount: 13 },
    { book: "Song of Solomon", chapter: 7, verseCount: 13 },
    { book: "Song of Solomon", chapter: 8, verseCount: 14 },
    { book: "Isaiah", chapter: 1, verseCount: 31 },
    { book: "Isaiah", chapter: 2, verseCount: 22 },
    { book: "Isaiah", chapter: 3, verseCount: 26 },
    { book: "Isaiah", chapter: 4, verseCount: 6 },
    { book: "Isaiah", chapter: 5, verseCount: 30 },
    { book: "Isaiah", chapter: 6, verseCount: 13 },
    { book: "Isaiah", chapter: 7, verseCount: 25 },
    { book: "Isaiah", chapter: 8, verseCount: 22 },
    { book: "Isaiah", chapter: 9, verseCount: 21 },
    { book: "Isaiah", chapter: 10, verseCount: 34 },
    { book: "Isaiah", chapter: 11, verseCount: 16 },
    { book: "Isaiah", chapter: 12, verseCount: 6 },
    { book: "Isaiah", chapter: 13, verseCount: 22 },
    { book: "Isaiah", chapter: 14, verseCount: 32 },
    { book: "Isaiah", chapter: 15, verseCount: 9 },
    { book: "Isaiah", chapter: 16, verseCount: 14 },
    { book: "Isaiah", chapter: 17, verseCount: 14 },
    { book: "Isaiah", chapter: 18, verseCount: 7 },
    { book: "Isaiah", chapter: 19, verseCount: 25 },
    { book: "Isaiah", chapter: 20, verseCount: 6 },
    { book: "Isaiah", chapter: 21, verseCount: 17 },
    { book: "Isaiah", chapter: 22, verseCount: 25 },
    { book: "Isaiah", chapter: 23, verseCount: 18 },
    { book: "Isaiah", chapter: 24, verseCount: 23 },
    { book: "Isaiah", chapter: 25, verseCount: 12 },
    { book: "Isaiah", chapter: 26, verseCount: 21 },
    { book: "Isaiah", chapter: 27, verseCount: 13 },
    { book: "Isaiah", chapter: 28, verseCount: 29 },
    { book: "Isaiah", chapter: 29, verseCount: 24 },
    { book: "Isaiah", chapter: 30, verseCount: 33 },
    { book: "Isaiah", chapter: 31, verseCount: 9 },
    { book: "Isaiah", chapter: 32, verseCount: 20 },
    { book: "Isaiah", chapter: 33, verseCount: 24 },
    { book: "Isaiah", chapter: 34, verseCount: 17 },
    { book: "Isaiah", chapter: 35, verseCount: 10 },
    { book: "Isaiah", chapter: 36, verseCount: 22 },
    { book: "Isaiah", chapter: 37, verseCount: 38 },
    { book: "Isaiah", chapter: 38, verseCount: 22 },
    { book: "Isaiah", chapter: 39, verseCount: 8 },
    { book: "Isaiah", chapter: 40, verseCount: 31 },
    { book: "Isaiah", chapter: 41, verseCount: 29 },
    { book: "Isaiah", chapter: 42, verseCount: 25 },
    { book: "Isaiah", chapter: 43, verseCount: 28 },
    { book: "Isaiah", chapter: 44, verseCount: 28 },
    { book: "Isaiah", chapter: 45, verseCount: 25 },
    { book: "Isaiah", chapter: 46, verseCount: 13 },
    { book: "Isaiah", chapter: 47, verseCount: 15 },
    { book: "Isaiah", chapter: 48, verseCount: 22 },
    { book: "Isaiah", chapter: 49, verseCount: 26 },
    { book: "Isaiah", chapter: 50, verseCount: 11 },
    { book: "Isaiah", chapter: 51, verseCount: 23 },
    { book: "Isaiah", chapter: 52, verseCount: 15 },
    { book: "Isaiah", chapter: 53, verseCount: 12 },
    { book: "Isaiah", chapter: 54, verseCount: 17 },
    { book: "Isaiah", chapter: 55, verseCount: 13 },
    { book: "Isaiah", chapter: 56, verseCount: 12 },
    { book: "Isaiah", chapter: 57, verseCount: 21 },
    { book: "Isaiah", chapter: 58, verseCount: 14 },
    { book: "Isaiah", chapter: 59, verseCount: 21 },
    { book: "Isaiah", chapter: 60, verseCount: 22 },
    { book: "Isaiah", chapter: 61, verseCount: 11 },
    { book: "Isaiah", chapter: 62, verseCount: 12 },
    { book: "Isaiah", chapter: 63, verseCount: 19 },
    { book: "Isaiah", chapter: 64, verseCount: 12 },
    { book: "Isaiah", chapter: 65, verseCount: 25 },
    { book: "Isaiah", chapter: 66, verseCount: 24 },
    { book: "Jeremiah", chapter: 1, verseCount: 19 },
    { book: "Jeremiah", chapter: 2, verseCount: 37 },
    { book: "Jeremiah", chapter: 3, verseCount: 25 },
    { book: "Jeremiah", chapter: 4, verseCount: 31 },
    { book: "Jeremiah", chapter: 5, verseCount: 31 },
    { book: "Jeremiah", chapter: 6, verseCount: 30 },
    { book: "Jeremiah", chapter: 7, verseCount: 34 },
    { book: "Jeremiah", chapter: 8, verseCount: 22 },
    { book: "Jeremiah", chapter: 9, verseCount: 26 },
    { book: "Jeremiah", chapter: 10, verseCount: 25 },
    { book: "Jeremiah", chapter: 11, verseCount: 23 },
    { book: "Jeremiah", chapter: 12, verseCount: 17 },
    { book: "Jeremiah", chapter: 13, verseCount: 27 },
    { book: "Jeremiah", chapter: 14, verseCount: 22 },
    { book: "Jeremiah", chapter: 15, verseCount: 21 },
    { book: "Jeremiah", chapter: 16, verseCount: 21 },
    { book: "Jeremiah", chapter: 17, verseCount: 27 },
    { book: "Jeremiah", chapter: 18, verseCount: 23 },
    { book: "Jeremiah", chapter: 19, verseCount: 15 },
    { book: "Jeremiah", chapter: 20, verseCount: 18 },
    { book: "Jeremiah", chapter: 21, verseCount: 14 },
    { book: "Jeremiah", chapter: 22, verseCount: 30 },
    { book: "Jeremiah", chapter: 23, verseCount: 40 },
    { book: "Jeremiah", chapter: 24, verseCount: 10 },
    { book: "Jeremiah", chapter: 25, verseCount: 38 },
    { book: "Jeremiah", chapter: 26, verseCount: 24 },
    { book: "Jeremiah", chapter: 27, verseCount: 22 },
    { book: "Jeremiah", chapter: 28, verseCount: 17 },
    { book: "Jeremiah", chapter: 29, verseCount: 32 },
    { book: "Jeremiah", chapter: 30, verseCount: 24 },
    { book: "Jeremiah", chapter: 31, verseCount: 40 },
    { book: "Jeremiah", chapter: 32, verseCount: 44 },
    { book: "Jeremiah", chapter: 33, verseCount: 26 },
    { book: "Jeremiah", chapter: 34, verseCount: 22 },
    { book: "Jeremiah", chapter: 35, verseCount: 19 },
    { book: "Jeremiah", chapter: 36, verseCount: 32 },
    { book: "Jeremiah", chapter: 37, verseCount: 21 },
    { book: "Jeremiah", chapter: 38, verseCount: 28 },
    { book: "Jeremiah", chapter: 39, verseCount: 18 },
    { book: "Jeremiah", chapter: 40, verseCount: 16 },
    { book: "Jeremiah", chapter: 41, verseCount: 18 },
    { book: "Jeremiah", chapter: 42, verseCount: 22 },
    { book: "Jeremiah", chapter: 43, verseCount: 13 },
    { book: "Jeremiah", chapter: 44, verseCount: 30 },
    { book: "Jeremiah", chapter: 45, verseCount: 5 },
    { book: "Jeremiah", chapter: 46, verseCount: 28 },
    { book: "Jeremiah", chapter: 47, verseCount: 7 },
    { book: "Jeremiah", chapter: 48, verseCount: 47 },
    { book: "Jeremiah", chapter: 49, verseCount: 39 },
    { book: "Jeremiah", chapter: 50, verseCount: 46 },
    { book: "Jeremiah", chapter: 51, verseCount: 64 },
    { book: "Jeremiah", chapter: 52, verseCount: 34 },
    { book: "Lamentations", chapter: 1, verseCount: 22 },
    { book: "Lamentations", chapter: 2, verseCount: 22 },
    { book: "Lamentations", chapter: 3, verseCount: 66 },
    { book: "Lamentations", chapter: 4, verseCount: 22 },
    { book: "Lamentations", chapter: 5, verseCount: 22 },
    { book: "Ezekiel", chapter: 1, verseCount: 28 },
    { book: "Ezekiel", chapter: 2, verseCount: 10 },
    { book: "Ezekiel", chapter: 3, verseCount: 27 },
    { book: "Ezekiel", chapter: 4, verseCount: 17 },
    { book: "Ezekiel", chapter: 5, verseCount: 17 },
    { book: "Ezekiel", chapter: 6, verseCount: 14 },
    { book: "Ezekiel", chapter: 7, verseCount: 27 },
    { book: "Ezekiel", chapter: 8, verseCount: 18 },
    { book: "Ezekiel", chapter: 9, verseCount: 11 },
    { book: "Ezekiel", chapter: 10, verseCount: 22 },
    { book: "Ezekiel", chapter: 11, verseCount: 25 },
    { book: "Ezekiel", chapter: 12, verseCount: 28 },
    { book: "Ezekiel", chapter: 13, verseCount: 23 },
    { book: "Ezekiel", chapter: 14, verseCount: 23 },
    { book: "Ezekiel", chapter: 15, verseCount: 8 },
    { book: "Ezekiel", chapter: 16, verseCount: 63 },
    { book: "Ezekiel", chapter: 17, verseCount: 24 },
    { book: "Ezekiel", chapter: 18, verseCount: 32 },
    { book: "Ezekiel", chapter: 19, verseCount: 14 },
    { book: "Ezekiel", chapter: 20, verseCount: 49 },
    { book: "Ezekiel", chapter: 21, verseCount: 32 },
    { book: "Ezekiel", chapter: 22, verseCount: 31 },
    { book: "Ezekiel", chapter: 23, verseCount: 49 },
    { book: "Ezekiel", chapter: 24, verseCount: 27 },
    { book: "Ezekiel", chapter: 25, verseCount: 17 },
    { book: "Ezekiel", chapter: 26, verseCount: 21 },
    { book: "Ezekiel", chapter: 27, verseCount: 36 },
    { book: "Ezekiel", chapter: 28, verseCount: 26 },
    { book: "Ezekiel", chapter: 29, verseCount: 21 },
    { book: "Ezekiel", chapter: 30, verseCount: 26 },
    { book: "Ezekiel", chapter: 31, verseCount: 18 },
    { book: "Ezekiel", chapter: 32, verseCount: 32 },
    { book: "Ezekiel", chapter: 33, verseCount: 33 },
    { book: "Ezekiel", chapter: 34, verseCount: 31 },
    { book: "Ezekiel", chapter: 35, verseCount: 15 },
    { book: "Ezekiel", chapter: 36, verseCount: 38 },
    { book: "Ezekiel", chapter: 37, verseCount: 28 },
    { book: "Ezekiel", chapter: 38, verseCount: 23 },
    { book: "Ezekiel", chapter: 39, verseCount: 29 },
    { book: "Ezekiel", chapter: 40, verseCount: 49 },
    { book: "Ezekiel", chapter: 41, verseCount: 26 },
    { book: "Ezekiel", chapter: 42, verseCount: 20 },
    { book: "Ezekiel", chapter: 43, verseCount: 27 },
    { book: "Ezekiel", chapter: 44, verseCount: 31 },
    { book: "Ezekiel", chapter: 45, verseCount: 25 },
    { book: "Ezekiel", chapter: 46, verseCount: 24 },
    { book: "Ezekiel", chapter: 47, verseCount: 23 },
    { book: "Ezekiel", chapter: 48, verseCount: 35 },
    { book: "Daniel", chapter: 1, verseCount: 21 },
    { book: "Daniel", chapter: 2, verseCount: 49 },
    { book: "Daniel", chapter: 3, verseCount: 30 },
    { book: "Daniel", chapter: 4, verseCount: 37 },
    { book: "Daniel", chapter: 5, verseCount: 31 },
    { book: "Daniel", chapter: 6, verseCount: 28 },
    { book: "Daniel", chapter: 7, verseCount: 28 },
    { book: "Daniel", chapter: 8, verseCount: 27 },
    { book: "Daniel", chapter: 9, verseCount: 27 },
    { book: "Daniel", chapter: 10, verseCount: 21 },
    { book: "Daniel", chapter: 11, verseCount: 45 },
    { book: "Daniel", chapter: 12, verseCount: 13 },
    { book: "Hosea", chapter: 1, verseCount: 11 },
    { book: "Hosea", chapter: 2, verseCount: 23 },
    { book: "Hosea", chapter: 3, verseCount: 5 },
    { book: "Hosea", chapter: 4, verseCount: 19 },
    { book: "Hosea", chapter: 5, verseCount: 15 },
    { book: "Hosea", chapter: 6, verseCount: 11 },
    { book: "Hosea", chapter: 7, verseCount: 16 },
    { book: "Hosea", chapter: 8, verseCount: 14 },
    { book: "Hosea", chapter: 9, verseCount: 17 },
    { book: "Hosea", chapter: 10, verseCount: 15 },
    { book: "Hosea", chapter: 11, verseCount: 12 },
    { book: "Hosea", chapter: 12, verseCount: 14 },
    { book: "Hosea", chapter: 13, verseCount: 16 },
    { book: "Hosea", chapter: 14, verseCount: 9 },
    { book: "Joel", chapter: 1, verseCount: 20 },
    { book: "Joel", chapter: 2, verseCount: 32 },
    { book: "Joel", chapter: 3, verseCount: 21 },
    { book: "Amos", chapter: 1, verseCount: 15 },
    { book: "Amos", chapter: 2, verseCount: 16 },
    { book: "Amos", chapter: 3, verseCount: 15 },
    { book: "Amos", chapter: 4, verseCount: 13 },
    { book: "Amos", chapter: 5, verseCount: 27 },
    { book: "Amos", chapter: 6, verseCount: 14 },
    { book: "Amos", chapter: 7, verseCount: 17 },
    { book: "Amos", chapter: 8, verseCount: 14 },
    { book: "Amos", chapter: 9, verseCount: 15 },
    { book: "Obadiah", chapter: 1, verseCount: 21 },
    { book: "Jonah", chapter: 1, verseCount: 17 },
    { book: "Jonah", chapter: 2, verseCount: 10 },
    { book: "Jonah", chapter: 3, verseCount: 10 },
    { book: "Jonah", chapter: 4, verseCount: 11 },
    { book: "Micah", chapter: 1, verseCount: 16 },
    { book: "Micah", chapter: 2, verseCount: 13 },
    { book: "Micah", chapter: 3, verseCount: 12 },
    { book: "Micah", chapter: 4, verseCount: 13 },
    { book: "Micah", chapter: 5, verseCount: 15 },
    { book: "Micah", chapter: 6, verseCount: 16 },
    { book: "Micah", chapter: 7, verseCount: 20 },
    { book: "Nahum", chapter: 1, verseCount: 15 },
    { book: "Nahum", chapter: 2, verseCount: 13 },
    { book: "Nahum", chapter: 3, verseCount: 19 },
    { book: "Habakkuk", chapter: 1, verseCount: 17 },
    { book: "Habakkuk", chapter: 2, verseCount: 20 },
    { book: "Habakkuk", chapter: 3, verseCount: 19 },
    { book: "Zephaniah", chapter: 1, verseCount: 18 },
    { book: "Zephaniah", chapter: 2, verseCount: 15 },
    { book: "Zephaniah", chapter: 3, verseCount: 20 },
    { book: "Haggai", chapter: 1, verseCount: 15 },
    { book: "Haggai", chapter: 2, verseCount: 23 },
    { book: "Zechariah", chapter: 1, verseCount: 21 },
    { book: "Zechariah", chapter: 2, verseCount: 13 },
    { book: "Zechariah", chapter: 3, verseCount: 10 },
    { book: "Zechariah", chapter: 4, verseCount: 14 },
    { book: "Zechariah", chapter: 5, verseCount: 11 },
    { book: "Zechariah", chapter: 6, verseCount: 15 },
    { book: "Zechariah", chapter: 7, verseCount: 14 },
    { book: "Zechariah", chapter: 8, verseCount: 23 },
    { book: "Zechariah", chapter: 9, verseCount: 17 },
    { book: "Zechariah", chapter: 10, verseCount: 12 },
    { book: "Zechariah", chapter: 11, verseCount: 17 },
    { book: "Zechariah", chapter: 12, verseCount: 14 },
    { book: "Zechariah", chapter: 13, verseCount: 9 },
    { book: "Zechariah", chapter: 14, verseCount: 21 },
    { book: "Malachi", chapter: 1, verseCount: 14 },
    { book: "Malachi", chapter: 2, verseCount: 17 },
    { book: "Malachi", chapter: 3, verseCount: 18 },
    { book: "Malachi", chapter: 4, verseCount: 6 },
    { book: "Matthew", chapter: 1, verseCount: 25 },
    { book: "Matthew", chapter: 2, verseCount: 23 },
    { book: "Matthew", chapter: 3, verseCount: 17 },
    { book: "Matthew", chapter: 4, verseCount: 25 },
    { book: "Matthew", chapter: 5, verseCount: 48 },
    { book: "Matthew", chapter: 6, verseCount: 34 },
    { book: "Matthew", chapter: 7, verseCount: 29 },
    { book: "Matthew", chapter: 8, verseCount: 34 },
    { book: "Matthew", chapter: 9, verseCount: 38 },
    { book: "Matthew", chapter: 10, verseCount: 42 },
    { book: "Matthew", chapter: 11, verseCount: 30 },
    { book: "Matthew", chapter: 12, verseCount: 50 },
    { book: "Matthew", chapter: 13, verseCount: 58 },
    { book: "Matthew", chapter: 14, verseCount: 36 },
    { book: "Matthew", chapter: 15, verseCount: 39 },
    { book: "Matthew", chapter: 16, verseCount: 28 },
    { book: "Matthew", chapter: 17, verseCount: 27 },
    { book: "Matthew", chapter: 18, verseCount: 35 },
    { book: "Matthew", chapter: 19, verseCount: 30 },
    { book: "Matthew", chapter: 20, verseCount: 34 },
    { book: "Matthew", chapter: 21, verseCount: 46 },
    { book: "Matthew", chapter: 22, verseCount: 46 },
    { book: "Matthew", chapter: 23, verseCount: 39 },
    { book: "Matthew", chapter: 24, verseCount: 51 },
    { book: "Matthew", chapter: 25, verseCount: 46 },
    { book: "Matthew", chapter: 26, verseCount: 75 },
    { book: "Matthew", chapter: 27, verseCount: 66 },
    { book: "Matthew", chapter: 28, verseCount: 20 },
    { book: "Mark", chapter: 1, verseCount: 45 },
    { book: "Mark", chapter: 2, verseCount: 28 },
    { book: "Mark", chapter: 3, verseCount: 35 },
    { book: "Mark", chapter: 4, verseCount: 41 },
    { book: "Mark", chapter: 5, verseCount: 43 },
    { book: "Mark", chapter: 6, verseCount: 56 },
    { book: "Mark", chapter: 7, verseCount: 37 },
    { book: "Mark", chapter: 8, verseCount: 38 },
    { book: "Mark", chapter: 9, verseCount: 50 },
    { book: "Mark", chapter: 10, verseCount: 52 },
    { book: "Mark", chapter: 11, verseCount: 33 },
    { book: "Mark", chapter: 12, verseCount: 44 },
    { book: "Mark", chapter: 13, verseCount: 37 },
    { book: "Mark", chapter: 14, verseCount: 72 },
    { book: "Mark", chapter: 15, verseCount: 47 },
    { book: "Mark", chapter: 16, verseCount: 20 },
    { book: "Luke", chapter: 1, verseCount: 80 },
    { book: "Luke", chapter: 2, verseCount: 52 },
    { book: "Luke", chapter: 3, verseCount: 38 },
    { book: "Luke", chapter: 4, verseCount: 44 },
    { book: "Luke", chapter: 5, verseCount: 39 },
    { book: "Luke", chapter: 6, verseCount: 49 },
    { book: "Luke", chapter: 7, verseCount: 50 },
    { book: "Luke", chapter: 8, verseCount: 56 },
    { book: "Luke", chapter: 9, verseCount: 62 },
    { book: "Luke", chapter: 10, verseCount: 42 },
    { book: "Luke", chapter: 11, verseCount: 54 },
    { book: "Luke", chapter: 12, verseCount: 59 },
    { book: "Luke", chapter: 13, verseCount: 35 },
    { book: "Luke", chapter: 14, verseCount: 35 },
    { book: "Luke", chapter: 15, verseCount: 32 },
    { book: "Luke", chapter: 16, verseCount: 31 },
    { book: "Luke", chapter: 17, verseCount: 37 },
    { book: "Luke", chapter: 18, verseCount: 43 },
    { book: "Luke", chapter: 19, verseCount: 48 },
    { book: "Luke", chapter: 20, verseCount: 47 },
    { book: "Luke", chapter: 21, verseCount: 38 },
    { book: "Luke", chapter: 22, verseCount: 71 },
    { book: "Luke", chapter: 23, verseCount: 56 },
    { book: "Luke", chapter: 24, verseCount: 55 },
    { book: "John", chapter: 1, verseCount: 51 },
    { book: "John", chapter: 2, verseCount: 25 },
    { book: "John", chapter: 3, verseCount: 36 },
    { book: "John", chapter: 4, verseCount: 54 },
    { book: "John", chapter: 5, verseCount: 47 },
    { book: "John", chapter: 6, verseCount: 71 },
    { book: "John", chapter: 7, verseCount: 53 },
    { book: "John", chapter: 8, verseCount: 59 },
    { book: "John", chapter: 9, verseCount: 41 },
    { book: "John", chapter: 10, verseCount: 42 },
    { book: "John", chapter: 11, verseCount: 57 },
    { book: "John", chapter: 12, verseCount: 50 },
    { book: "John", chapter: 13, verseCount: 38 },
    { book: "John", chapter: 14, verseCount: 31 },
    { book: "John", chapter: 15, verseCount: 27 },
    { book: "John", chapter: 16, verseCount: 33 },
    { book: "John", chapter: 17, verseCount: 26 },
    { book: "John", chapter: 18, verseCount: 40 },
    { book: "John", chapter: 19, verseCount: 42 },
    { book: "John", chapter: 20, verseCount: 31 },
    { book: "John", chapter: 21, verseCount: 25 },
    { book: "Acts", chapter: 1, verseCount: 26 },
    { book: "Acts", chapter: 2, verseCount: 47 },
    { book: "Acts", chapter: 3, verseCount: 26 },
    { book: "Acts", chapter: 4, verseCount: 37 },
    { book: "Acts", chapter: 5, verseCount: 42 },
    { book: "Acts", chapter: 6, verseCount: 15 },
    { book: "Acts", chapter: 7, verseCount: 60 },
    { book: "Acts", chapter: 8, verseCount: 40 },
    { book: "Acts", chapter: 9, verseCount: 43 },
    { book: "Acts", chapter: 10, verseCount: 48 },
    { book: "Acts", chapter: 11, verseCount: 30 },
    { book: "Acts", chapter: 12, verseCount: 25 },
    { book: "Acts", chapter: 13, verseCount: 52 },
    { book: "Acts", chapter: 14, verseCount: 28 },
    { book: "Acts", chapter: 15, verseCount: 41 },
    { book: "Acts", chapter: 16, verseCount: 40 },
    { book: "Acts", chapter: 17, verseCount: 34 },
    { book: "Acts", chapter: 18, verseCount: 28 },
    { book: "Acts", chapter: 19, verseCount: 41 },
    { book: "Acts", chapter: 20, verseCount: 38 },
    { book: "Acts", chapter: 21, verseCount: 40 },
    { book: "Acts", chapter: 22, verseCount: 30 },
    { book: "Acts", chapter: 23, verseCount: 35 },
    { book: "Acts", chapter: 24, verseCount: 27 },
    { book: "Acts", chapter: 25, verseCount: 27 },
    { book: "Acts", chapter: 26, verseCount: 32 },
    { book: "Acts", chapter: 27, verseCount: 44 },
    { book: "Acts", chapter: 28, verseCount: 31 },
    { book: "Romans", chapter: 1, verseCount: 32 },
    { book: "Romans", chapter: 2, verseCount: 29 },
    { book: "Romans", chapter: 3, verseCount: 31 },
    { book: "Romans", chapter: 4, verseCount: 25 },
    { book: "Romans", chapter: 5, verseCount: 21 },
    { book: "Romans", chapter: 6, verseCount: 23 },
    { book: "Romans", chapter: 7, verseCount: 25 },
    { book: "Romans", chapter: 8, verseCount: 39 },
    { book: "Romans", chapter: 9, verseCount: 33 },
    { book: "Romans", chapter: 10, verseCount: 21 },
    { book: "Romans", chapter: 11, verseCount: 36 },
    { book: "Romans", chapter: 12, verseCount: 21 },
    { book: "Romans", chapter: 13, verseCount: 14 },
    { book: "Romans", chapter: 14, verseCount: 23 },
    { book: "Romans", chapter: 15, verseCount: 33 },
    { book: "Romans", chapter: 16, verseCount: 27 },
    { book: "1 Corinthians", chapter: 1, verseCount: 31 },
    { book: "1 Corinthians", chapter: 2, verseCount: 16 },
    { book: "1 Corinthians", chapter: 3, verseCount: 23 },
    { book: "1 Corinthians", chapter: 4, verseCount: 21 },
    { book: "1 Corinthians", chapter: 5, verseCount: 13 },
    { book: "1 Corinthians", chapter: 6, verseCount: 20 },
    { book: "1 Corinthians", chapter: 7, verseCount: 40 },
    { book: "1 Corinthians", chapter: 8, verseCount: 13 },
    { book: "1 Corinthians", chapter: 9, verseCount: 27 },
    { book: "1 Corinthians", chapter: 10, verseCount: 33 },
    { book: "1 Corinthians", chapter: 11, verseCount: 34 },
    { book: "1 Corinthians", chapter: 12, verseCount: 31 },
    { book: "1 Corinthians", chapter: 13, verseCount: 13 },
    { book: "1 Corinthians", chapter: 14, verseCount: 40 },
    { book: "1 Corinthians", chapter: 15, verseCount: 58 },
    { book: "1 Corinthians", chapter: 16, verseCount: 24 },
    { book: "2 Corinthians", chapter: 1, verseCount: 24 },
    { book: "2 Corinthians", chapter: 2, verseCount: 17 },
    { book: "2 Corinthians", chapter: 3, verseCount: 18 },
    { book: "2 Corinthians", chapter: 4, verseCount: 18 },
    { book: "2 Corinthians", chapter: 5, verseCount: 21 },
    { book: "2 Corinthians", chapter: 6, verseCount: 18 },
    { book: "2 Corinthians", chapter: 7, verseCount: 16 },
    { book: "2 Corinthians", chapter: 8, verseCount: 24 },
    { book: "2 Corinthians", chapter: 9, verseCount: 15 },
    { book: "2 Corinthians", chapter: 10, verseCount: 18 },
    { book: "2 Corinthians", chapter: 11, verseCount: 33 },
    { book: "2 Corinthians", chapter: 12, verseCount: 21 },
    { book: "2 Corinthians", chapter: 13, verseCount: 14 },
    { book: "Galatians", chapter: 1, verseCount: 24 },
    { book: "Galatians", chapter: 2, verseCount: 21 },
    { book: "Galatians", chapter: 3, verseCount: 29 },
    { book: "Galatians", chapter: 4, verseCount: 31 },
    { book: "Galatians", chapter: 5, verseCount: 26 },
    { book: "Galatians", chapter: 6, verseCount: 18 },
    { book: "Ephesians", chapter: 1, verseCount: 23 },
    { book: "Ephesians", chapter: 2, verseCount: 22 },
    { book: "Ephesians", chapter: 3, verseCount: 21 },
    { book: "Ephesians", chapter: 4, verseCount: 32 },
    { book: "Ephesians", chapter: 5, verseCount: 33 },
    { book: "Ephesians", chapter: 6, verseCount: 24 },
    { book: "Philippians", chapter: 1, verseCount: 30 },
    { book: "Philippians", chapter: 2, verseCount: 30 },
    { book: "Philippians", chapter: 3, verseCount: 21 },
    { book: "Philippians", chapter: 4, verseCount: 23 },
    { book: "Colossians", chapter: 1, verseCount: 29 },
    { book: "Colossians", chapter: 2, verseCount: 23 },
    { book: "Colossians", chapter: 3, verseCount: 25 },
    { book: "Colossians", chapter: 4, verseCount: 18 },
    { book: "1 Thessalonians", chapter: 1, verseCount: 10 },
    { book: "1 Thessalonians", chapter: 2, verseCount: 20 },
    { book: "1 Thessalonians", chapter: 3, verseCount: 13 },
    { book: "1 Thessalonians", chapter: 4, verseCount: 18 },
    { book: "1 Thessalonians", chapter: 5, verseCount: 28 },
    { book: "2 Thessalonians", chapter: 1, verseCount: 12 },
    { book: "2 Thessalonians", chapter: 2, verseCount: 17 },
    { book: "2 Thessalonians", chapter: 3, verseCount: 18 },
    { book: "1 Timothy", chapter: 1, verseCount: 20 },
    { book: "1 Timothy", chapter: 2, verseCount: 15 },
    { book: "1 Timothy", chapter: 3, verseCount: 16 },
    { book: "1 Timothy", chapter: 4, verseCount: 16 },
    { book: "1 Timothy", chapter: 5, verseCount: 25 },
    { book: "1 Timothy", chapter: 6, verseCount: 21 },
    { book: "2 Timothy", chapter: 1, verseCount: 18 },
    { book: "2 Timothy", chapter: 2, verseCount: 26 },
    { book: "2 Timothy", chapter: 3, verseCount: 17 },
    { book: "2 Timothy", chapter: 4, verseCount: 22 },
    { book: "Titus", chapter: 1, verseCount: 16 },
    { book: "Titus", chapter: 2, verseCount: 15 },
    { book: "Titus", chapter: 3, verseCount: 15 },
    { book: "Philemon", chapter: 1, verseCount: 25 },
    { book: "Hebrews", chapter: 1, verseCount: 14 },
    { book: "Hebrews", chapter: 2, verseCount: 18 },
    { book: "Hebrews", chapter: 3, verseCount: 19 },
    { book: "Hebrews", chapter: 4, verseCount: 16 },
    { book: "Hebrews", chapter: 5, verseCount: 14 },
    { book: "Hebrews", chapter: 6, verseCount: 20 },
    { book: "Hebrews", chapter: 7, verseCount: 28 },
    { book: "Hebrews", chapter: 8, verseCount: 13 },
    { book: "Hebrews", chapter: 9, verseCount: 28 },
    { book: "Hebrews", chapter: 10, verseCount: 39 },
    { book: "Hebrews", chapter: 11, verseCount: 40 },
    { book: "Hebrews", chapter: 12, verseCount: 29 },
    { book: "Hebrews", chapter: 13, verseCount: 25 },
    { book: "James", chapter: 1, verseCount: 27 },
    { book: "James", chapter: 2, verseCount: 26 },
    { book: "James", chapter: 3, verseCount: 18 },
    { book: "James", chapter: 4, verseCount: 17 },
    { book: "James", chapter: 5, verseCount: 20 },
    { book: "1 Peter", chapter: 1, verseCount: 25 },
    { book: "1 Peter", chapter: 2, verseCount: 25 },
    { book: "1 Peter", chapter: 3, verseCount: 22 },
    { book: "1 Peter", chapter: 4, verseCount: 19 },
    { book: "1 Peter", chapter: 5, verseCount: 14 },
    { book: "2 Peter", chapter: 1, verseCount: 21 },
    { book: "2 Peter", chapter: 2, verseCount: 22 },
    { book: "2 Peter", chapter: 3, verseCount: 18 },
    { book: "1 John", chapter: 1, verseCount: 10 },
    { book: "1 John", chapter: 2, verseCount: 29 },
    { book: "1 John", chapter: 3, verseCount: 24 },
    { book: "1 John", chapter: 4, verseCount: 21 },
    { book: "1 John", chapter: 5, verseCount: 21 },
    { book: "2 John", chapter: 1, verseCount: 13 },
    { book: "3 John", chapter: 1, verseCount: 14 },
    { book: "Jude", chapter: 1, verseCount: 25 },
    { book: "Revelation", chapter: 1, verseCount: 20 },
    { book: "Revelation", chapter: 2, verseCount: 29 },
    { book: "Revelation", chapter: 3, verseCount: 22 },
    { book: "Revelation", chapter: 4, verseCount: 11 },
    { book: "Revelation", chapter: 5, verseCount: 14 },
    { book: "Revelation", chapter: 6, verseCount: 17 },
    { book: "Revelation", chapter: 7, verseCount: 17 },
    { book: "Revelation", chapter: 8, verseCount: 13 },
    { book: "Revelation", chapter: 9, verseCount: 21 },
    { book: "Revelation", chapter: 10, verseCount: 11 },
    { book: "Revelation", chapter: 11, verseCount: 19 },
    { book: "Revelation", chapter: 12, verseCount: 17 },
    { book: "Revelation", chapter: 13, verseCount: 18 },
    { book: "Revelation", chapter: 14, verseCount: 20 },
    { book: "Revelation", chapter: 15, verseCount: 8 },
    { book: "Revelation", chapter: 16, verseCount: 21 },
    { book: "Revelation", chapter: 17, verseCount: 18 },
    { book: "Revelation", chapter: 18, verseCount: 24 },
    { book: "Revelation", chapter: 19, verseCount: 21 },
    { book: "Revelation", chapter: 20, verseCount: 15 },
    { book: "Revelation", chapter: 21, verseCount: 27 },
    { book: "Revelation", chapter: 22, verseCount: 21 }
]
